# PyTorch
PyTorch is an open source machine learning library used for developing and training neural network based deep learning models, initially developed by Facebook’s AI research group.

Pytorch uses core Python concepts like classes, structures and conditional loops — that are a lot familiar to our eyes, hence a lot more intuitive to understand.

In [19]:
import torch 
import numpy as np 

print('Pytorch version: ', torch.__version__)

Pytorch version:  1.13.0+cu117


## Creating Tensors in Pytorch
**Tensor** : is the primary data structure used by neural network.

In [6]:
s = 3
scalar = torch.tensor(s) #scalar 
scalar

tensor(3)

In [7]:
scalar.ndim

0

In [11]:
scalar.item() #only work with one number 

3

In [14]:
a = [1, 2, 3] 
b = np.array([4, 5, 6], dtype = np.int32) 

vector_a = torch.tensor(a) #vector
print('tensor a: ', t_a)

vector_b = torch.tensor(b) #vector
print('tensor b: ', t_b)

tensor a:  tensor([1, 2, 3])
tensor b:  tensor([4, 5, 6], dtype=torch.int32)


**Axis:** refers to a specific dimension.

**Rank:** refers to the no. dimensions present within the tensor.

**Shape:** gives us the length of each axis of the tensor.

In [15]:
print('Dim of tensor a: ', vector_a.ndim)

print('Shape of tensor a: ', vector_a.shape)

Dim of tensor a:  1
Shape of tensor a:  torch.Size([3])


In [3]:
torch.is_tensor(a), torch.is_tensor(vector_a)

(False, True)

In [16]:
t_zeros = torch.zeros(2,3)
t_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

- A scalar is a **0** dimensional tensor
- A vector is a **1** dimensional tensor
- A matrix is a **2** dimensional tensor
- A nd-array is an **n** dimensional tensor

In [17]:
t_zeros.ndim #matrix

2

In [4]:
t_ones = torch.ones(2,3)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
#random tensor
rand_tensor = torch.rand(2,3)
rand_tensor

tensor([[0.5158, 0.5249, 0.6735],
        [0.1076, 0.0180, 0.6301]])

In [21]:
Matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print('Matrix: \n', Matrix)
print('Matrix Rank: ', Matrix.ndim)
print('Matrix shape: ', Matrix.shape)

Matrix: 
 tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix Rank:  2
Matrix shape:  torch.Size([2, 3])


## Manipulating the data type and shape of a tensor

In [23]:
vector_a_new = vector_a.to(torch.int64)
vector_a_new.dtype

torch.int64

In [32]:
t = torch.zeros(30)

t_reshape = t.reshape(5, 6)
print(t_reshape.shape)

torch.Size([5, 6])


**Squeezing:** a tensor removes the dimensions or axes that have a length of one. 

**Unsqueezing:** a tensor adds a dimension with a length of one.

In [44]:
t = torch.tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
print('Tensor before Squeezing: \n', t.shape)
print(t,'\n')
t_sqz = torch.squeeze(t)
print('Tnesor after Squeezing: \n', t_sqz.shape)
print(t_sqz,'\n')

Tensor before Squeezing: 
 torch.Size([1, 12])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]]) 

Tnesor after Squeezing: 
 torch.Size([12])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]) 



## Random Tensor

In [46]:
random_tensor = torch.rand(size=(4, 5))
random_tensor ,random_tensor.dtype 

(tensor([[0.3922, 0.2395, 0.7743, 0.4131, 0.0291],
         [0.2647, 0.5665, 0.7526, 0.3133, 0.9013],
         [0.0427, 0.3200, 0.8076, 0.2154, 0.7629],
         [0.8414, 0.4784, 0.4156, 0.0627, 0.6901]]),
 torch.float32)

In [47]:
#we can see the device type on which tensor is stored: 
random_tensor.device

device(type='cpu')

In [51]:
rand1 = torch.rand(size=(224, 224, 3))
rand1.shape, rand1.ndim

(torch.Size([224, 224, 3]), 3)

In [52]:
t = torch.rand(3, 5)

t_trans = torch.transpose(t, 0, 1)
print(t.shape, '-->', t_trans.shape)

torch.Size([3, 5]) --> torch.Size([5, 3])


## Create range in tensors

In [53]:
range1 = torch.arange(0, 10)
range1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
range2 = torch.arange(0, 10, 3)
range2

tensor([0, 3, 6, 9])

In [56]:
#we can also create a tensor of zeros similar to another tensor
zeros = torch.zeros_like(input=range2) #will have the same shape 
zeros 

tensor([0, 0, 0, 0])

In [59]:
float_tensor = torch.tensor([3.0, 5.0, 7.0], 
                           dtype = None, #defaults to None, which is torch.float32 or whatever datatype is passed
                           device = None, #defaults to None, which uses the default tensor device
                           requires_grad = False #if True, operations perfromed on the tensor are recorded
                           )
float_tensor.shape, float_tensor.dtype, float_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## Tensor Operations

In [61]:
tensor = torch.tensor([1, 3, 5])
tensor + 10, tensor*10

tensor([11, 13, 15])

In [62]:
# We can also use torch.mul() / torch.multiply()
torch.mul(tensor, 10)

tensor([10, 30, 50])

In [65]:
torch.manual_seed(1)

t1 = 2 * torch.rand(5, 2) - 1
t1

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

In [66]:
t2 = torch.normal(mean = 0, std = 1, size = (5,2))
t2

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])

In [72]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
norm_t1

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])

## Find the min, max, mean and sum 

In [74]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [75]:
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')
print(f'Sum: {x.sum()}')

Minimum: 0
Maximum: 90
Sum: 450


In [76]:
# We can also calculate min, max, sum, mean as below
torch.min(x), torch.max(x), torch.sum(x), torch.mean(x.type(torch.float32))

(tensor(0), tensor(90), tensor(450), tensor(45.))

In [78]:
print(f'Mean: {x.type(torch.float32).mean()}')

Mean: 45.0


## Split, Stack and concatenate

In [84]:
torch.manual_seed(1)

t = torch.rand(6)
print('Tensor: ', t)

t_splits = torch.chunk(t, 6) #6 splits
[item.numpy() for item in t_splits]

Tensor:  tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


[array([0.7576316], dtype=float32),
 array([0.27931088], dtype=float32),
 array([0.40306926], dtype=float32),
 array([0.73468447], dtype=float32),
 array([0.02928156], dtype=float32),
 array([0.7998586], dtype=float32)]

In [90]:
torch.manual_seed(1)

t = torch.rand(5)
print('Tensor: ', t)

t_splits = torch.split(t, split_size_or_sections=(3, 2))
t_splits

Tensor:  tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


(tensor([0.7576, 0.2793, 0.4031]), tensor([0.7347, 0.0293]))

In [92]:
A = torch.ones(3)
B = torch.zeros(3)

A, B

(tensor([1., 1., 1.]), tensor([0., 0., 0.]))

In [93]:
torch.cat([A, B])

tensor([1., 1., 1., 0., 0., 0.])

In [96]:
torch.cat([A, B], axis=0)

tensor([1., 1., 1., 0., 0., 0.])

In [98]:
torch.stack([A, B], axis = 0)

tensor([[1., 1., 1.],
        [0., 0., 0.]])

In [110]:
torch.stack([A, B], dim = 0)

tensor([[1., 1., 1.],
        [0., 0., 0.]])

In [99]:
torch.stack([A, B], axis = 1)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])

In [100]:
torch.vstack((A,B))

tensor([[1., 1., 1.],
        [0., 0., 0.]])

In [101]:
torch.hstack((A,B))

tensor([1., 1., 1., 0., 0., 0.])

### Flatten A Tensor
A flatten operation on a tensor reshapes the tensor to have a shape that is equal to the number of elements contained in the tensor. This is the same thing as a 1d-array of elements.

In [107]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

t = torch.ones(4, 3)
print('Before Flatting: \n', t)
print(t.shape)

print('After Flatten: ',flatten(t))
print(flatten(t).shape)

Before Flatting: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])
After Flatten:  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([12])


In [108]:
#Or
torch.flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Element-Wise Tensor Operations 
operates on corresponding elements between tensors.

In [171]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
          ], dtype=torch.float32)

In [173]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [175]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [176]:
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [177]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

### Some Terminology
There are some other ways to refer to element-wise operations, so I just wanted to mention that all of these mean the same thing:

- Element-wise
- Component-wise
- Point-wise

## Tensor Reduction Operations:
is an operation that reduces the number of elements contained within the tensor. 
- Tensors give us the ability to manage our data.

In [161]:
t = torch.tensor([
    [1,0,0],
    [0,2,0],
    [3,0,0]
          ], dtype=torch.float32)  #3x3 rank-2 tensor.

All of these tensor methods reduce the tensor to a single element scalar valued tensor by operating on all the tensor's elements.

In [162]:
t.sum()

tensor(6.)

In [163]:
t.numel()

9

In [164]:
t.prod()

tensor(0.)

In [165]:
t.mean()

tensor(0.6667)

In [166]:
t.std()

tensor(1.1180)

In [167]:
#Argmax returns the index location of the maximum value inside a tensor.
t.argmax()

tensor(6)

In [168]:
t.argmax().item()

6

In [169]:
t.argmax(dim=0)

tensor([2, 1, 0])

In [170]:
t.argmax(dim=1)

tensor([0, 1, 0])